config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'homes/about'
  end
	devise_for :admins, controllers: {
		sessions:      'admin/sessions',
		passwords:     'admin/passwords',
	}

	devise_for :users, controllers: {
		sessions: 'public/sessions',
		passwords:     'public/passwords',
		registrations: 'public/registrations',
	}

	namespace :admin do

		root 'photos#index'
		resources :photos, only: [:show, :edit, :update] do
			resources :comments, only: [:update]
		end

		resources :users, only: [:index, :show]
		put 'users/:id' => 'users#update', as: 'user_update'
		get 'users/:id/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:id/followers' => 'relationships#followers', as: 'user_followers'

		get 'comments' => 'comments#index', as: 'comments'

	end

	scope module: :public do

		root 'photos#index'
		resources :photos, only: [:new, :create, :show, :edit, :update, :destroy] do
			resources :comments, only: [:create, :edit, :update, :destroy]
			resource :favorites, only: [:create, :destroy]
		end

		get 'about' => 'homes#about', as: 'about'

		get 'users/:name' => 'users#show', as: 'user'
		get 'users/:name/edit' => 'users#edit', as: 'user_edit'
		patch 'users/:name' => 'users#update'

		get 'users/:name/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:name/followers' => 'relationships#followers', as: 'user_followers'
		post 'follow/:name' => 'relationships#create', as: 'follow'
		delete 'unfollow/:name' => 'relationships#destroy', as: 'unfollow'

		get 'search' => 'photos#search', as: 'search'

		resources :inquiries, only: [:create]
		get 'contact' => 'inquiries#new', as: 'contact'
		get 'contact/finish' => 'inquiries#finish', as: 'contact_finish'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment, presence: true,
            length: { maximum: 140 }


  belongs_to :user
  belongs_to :photo

  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @comments = Comment.all.order("created_at DESC")
  end

  def update
    comment = Comment.find(params[:id])
    if comment.is_active == true
      comment.update(is_active: false)
      redirect_back(fallback_location: root_path)
    else
      comment.update(is_active: true)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">

  <div class="admin_comment-index">
    <h2 class="admin_comment-index-name">Comments</h2>

    <table class="admin_comment-index-table">

      <% @comments.each do |comment| %>
        <tr>
          <td class="admin_comment-index-table-image">
            <%= link_to admin_photo_path(comment.photo.id) do %>
              <%= attachment_image_tag comment.photo, :image, class: "admin_comment-index-table-image-content", format: 'jpeg' %>
            <% end %>
          </td>
          <td class="admin_comment-index-table-name"><%= comment.user.name %></td>
          <td class="admin_comment-index-table-comment"><%= comment.comment %></td>
          <td class="admin_comment-index-table-date"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></td>
          <td class="admin_comment-index-table-btn">
            <% if comment.is_active == true %>
              <%= link_to 'Open', admin_photo_comment_path(comment.photo, comment), method: :PUT, class: "btn admin_comment-index-table-btn-open" %>
            <% else %>
              <%= link_to 'Hide', admin_photo_comment_path(comment.photo, comment), method: :PUT, class: "btn admin_comment-index-table-btn-hide" %>
            <% end %>
          </td>
        </tr>
      <% end %>

    </table>

  </div>

</div>