config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'homes/about'
  end
	devise_for :admins, controllers: {
		sessions:      'admin/sessions',
		passwords:     'admin/passwords',
	}

	devise_for :users, controllers: {
		sessions: 'public/sessions',
		passwords:     'public/passwords',
		registrations: 'public/registrations',
	}

	namespace :admin do

		root 'photos#index'
		resources :photos, only: [:show, :edit, :update] do
			resources :comments, only: [:update]
		end

		resources :users, only: [:index, :show]
		put 'users/:id' => 'users#update', as: 'user_update'
		get 'users/:id/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:id/followers' => 'relationships#followers', as: 'user_followers'

		get 'comments' => 'comments#index', as: 'comments'

	end

	scope module: :public do

		root 'photos#index'
		resources :photos, only: [:new, :create, :show, :edit, :update, :destroy] do
			resources :comments, only: [:create, :edit, :update, :destroy]
			resource :favorites, only: [:create, :destroy]
		end

		get 'about' => 'homes#about', as: 'about'

		get 'users/:name' => 'users#show', as: 'user'
		get 'users/:name/edit' => 'users#edit', as: 'user_edit'
		patch 'users/:name' => 'users#update'

		get 'users/:name/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:name/followers' => 'relationships#followers', as: 'user_followers'
		post 'follow/:name' => 'relationships#create', as: 'follow'
		delete 'unfollow/:name' => 'relationships#destroy', as: 'unfollow'

		get 'search' => 'photos#search', as: 'search'

		resources :inquiries, only: [:create]
		get 'contact' => 'inquiries#new', as: 'contact'
		get 'contact/finish' => 'inquiries#finish', as: 'contact_finish'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord

  validates :image, presence:true

  attachment :image
  acts_as_taggable

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController

  before_action :authenticate_admin!
  before_action :ensure_admin_photo, only: [:show, :update]

  def index
    @photos = Photo.all
  end

  def show
    @comments = @photo.comments
  end

  def update
    if @photo.is_active == true
      @photo.update(is_active: false)
      redirect_to admin_photo_path
    else
      @photo.update(is_active: true)
      redirect_to admin_photo_path
    end
  end

  private

  def ensure_admin_photo
    @photo = Photo.find(params[:id])
  end

end

app/views/admin/photos/index.html.erb
<div class="container">

  <div class="admin_photo-index mx-auto">
    <div class="row">
      <% @photos.each do |photo| %>
        <div class="col-md-3 px-0">
          <%= link_to admin_photo_path(photo.id), class: "admin_photo-index-content" do %>
            <%= attachment_image_tag photo, :image, style: 'width: 95%;', format: 'jpeg' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/photos/show.html.erb
<div class="container">

  <div class="admin_photo-show">
    <div class="row">

      <div class="col-md-5">
        <div class="admin_photo-show-user">
          <%= link_to admin_user_path(@photo.user), class: "admin_photo-show-user-link" do %>
            <%= attachment_image_tag @photo.user, :image, class: "admin_photo-show-user", format: 'jpeg' %>
            <span><%= @photo.user.name %></span>
          <% end %>
        </div>
        <div class="admin_photo-show-image">
          <%= attachment_image_tag @photo, :image, class: "admin_photo-show-image-content", format: 'jpeg' %>
        </div>

        <div class="admin_field-photo-show">
          <div class="row">
            <div class="admin_photo-show-favorite col-md-4">
              <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= @photo.favorites.count %>
            </div>

            <div class="admin_actions-photo-show col-md-4 offset-md-4 px-0">
              <% if @photo.is_active == true %>
                <%= link_to 'Open', admin_photo_path, class: "btn admin_actions-photo-show-open", method: :PUT %>
              <% else %>
                <%= link_to 'Hide', admin_photo_path, class: "btn admin_actions-photo-show-hide", method: :PUT %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="admin_field-photo-show">
          <div class="admin_photo-show-text">
            <%= @photo.text %>
          </div>
        </div>

        <div class="admin_field-photo-show">
          <div class="admin_photo-show-tag">
            <% @photo.tag_list.each do |tag| %>
              <span class="admin_photo-show-tag-content"><%= tag %></span>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-7">

        <% @comments.each do |comment| %>
          <div class="admin_photo-show-comment">
            <span id="admin_star-rate-<%= comment.id %>" class="admin_photo-show-comment-star"></span>
            <span class="float-right">
              <%= link_to admin_user_path(comment.user), class: "admin_photo-show-comment-link" do %>
                <%= comment.user.name %>
              <% end %>
            </span>
              <script>
                $('#admin_star-rate-<%= comment.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= comment.star %>,
                });
              </script>

            <div class="admin_photo-show-comment-content">
              <%= comment.comment %>
            </div>

            <div class="admin_photo-show-comment-btn">
              <% if comment.is_active == true %>
                <%= link_to 'Open', admin_photo_comment_path(comment.photo, comment), class: "btn admin_photo-comment-btn-open", method: :PUT %>
              <% else %>
                <%= link_to 'Hide', admin_photo_comment_path(comment.photo, comment), class: "btn admin_photo-comment-btn-hide", method: :PUT %>
              <% end %>
            </div>
          </div>
        <% end %>

      </div>

    </div>
  </div>

</div>