config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'homes/about'
  end
	devise_for :admins, controllers: {
		sessions:      'admin/sessions',
		passwords:     'admin/passwords',
	}

	devise_for :users, controllers: {
		sessions: 'public/sessions',
		passwords:     'public/passwords',
		registrations: 'public/registrations',
	}

	namespace :admin do

		root 'photos#index'
		resources :photos, only: [:show, :edit, :update] do
			resources :comments, only: [:update]
		end

		resources :users, only: [:index, :show]
		put 'users/:id' => 'users#update', as: 'user_update'
		get 'users/:id/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:id/followers' => 'relationships#followers', as: 'user_followers'

		get 'comments' => 'comments#index', as: 'comments'

	end

	scope module: :public do

		root 'photos#index'
		resources :photos, only: [:new, :create, :show, :edit, :update, :destroy] do
			resources :comments, only: [:create, :edit, :update, :destroy]
			resource :favorites, only: [:create, :destroy]
		end

		get 'about' => 'homes#about', as: 'about'

		get 'users/:name' => 'users#show', as: 'user'
		get 'users/:name/edit' => 'users#edit', as: 'user_edit'
		patch 'users/:name' => 'users#update'

		get 'users/:name/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:name/followers' => 'relationships#followers', as: 'user_followers'
		post 'follow/:name' => 'relationships#create', as: 'follow'
		delete 'unfollow/:name' => 'relationships#destroy', as: 'unfollow'

		get 'search' => 'photos#search', as: 'search'

		resources :inquiries, only: [:create]
		get 'contact' => 'inquiries#new', as: 'contact'
		get 'contact/finish' => 'inquiries#finish', as: 'contact_finish'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment, presence: true,
            length: { maximum: 140 }


  belongs_to :user
  belongs_to :photo

  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :photo

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord

  validates :image, presence:true

  attachment :image
  acts_as_taggable

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true,
           length: { maximum: 10 }

  attachment :image

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローされている人
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower

  # フォローした人
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @comments = Comment.all.order("created_at DESC")
  end

  def update
    comment = Comment.find(params[:id])
    if comment.is_active == true
      comment.update(is_active: false)
      redirect_back(fallback_location: root_path)
    else
      comment.update(is_active: true)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController

  before_action :authenticate_admin!
  before_action :ensure_admin_photo, only: [:show, :update]

  def index
    @photos = Photo.all
  end

  def show
    @comments = @photo.comments
  end

  def update
    if @photo.is_active == true
      @photo.update(is_active: false)
      redirect_to admin_photo_path
    else
      @photo.update(is_active: true)
      redirect_to admin_photo_path
    end
  end

  private

  def ensure_admin_photo
    @photo = Photo.find(params[:id])
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!
  before_action :ensure_admin_user, only: [:show, :update]

  def index
    @users = User.all
  end

  def show
    @photos = @user.photos
  end

  def update
    if @user.is_active == true
      @user.update(is_active: false)
      redirect_back(fallback_location: root_path)
    else
      @user.update(is_active: true)
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def ensure_admin_user
    @user = User.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def after_sign_up_path_for(resource)
		root_path
	end

	def after_sign_in_path_for(resource)
		root_path
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
	end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">

    <% if admin_signed_in? %>
        <%= image_tag 'nanimiru-logo.png', size: "150x50" %>
        <ul class="navbar-nav text-right pr-4">
          <li class="nav-item mx-2">
            <%= link_to admin_root_path, class: "nav-link" do %>
              <i class="far fa-images"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to admin_users_path, class: "nav-link" do %>
              <i class="fas fa-users"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to admin_comments_path, class: "nav-link" do %>
              <i class="far fa-comments"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        </ul>

    <% else %>

      <% if user_signed_in? %>
        <%= link_to root_path do %>
          <%= image_tag 'nanimiru-logo.png', size: "150x50" %>
        <% end %>
        <ul class="navbar-nav text-right pr-4">
          <li class="nav-item mx-2">
            <%= link_to user_path(current_user.name), class: "nav-link" do %>
              <i class="fas fa-user"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to new_photo_path, class: "nav-link" do %>
              <i class="far fa-plus-square"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to search_path, class: "nav-link" do %>
              <i class="fas fa-search"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to contact_path, class: "nav-link" do %>
              <i class="far fa-envelope"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        </ul>

      <% else %>
        <%= image_tag 'nanimiru-logo.png', size: "150x50" %>
        <ul class="navbar-nav text-right pr-4">
          <li class="nav-item mx-2">
            <%= link_to root_path, class: "nav-link" do %>
              <i class="far fa-images"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to about_path, class: "nav-link" do %>
              <i class="fas fa-question"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to search_path, class: "nav-link" do %>
              <i class="fas fa-search"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to contact_path, class: "nav-link" do %>
              <i class="far fa-envelope"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fas fa-sign-in-alt"></i>
            <% end %>
          </li>
          <li class="nav-item mx-2">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              <i class="fas fa-user-plus"></i>
            <% end %>
          </li>
        </ul>
      <% end %>

    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nanimiru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navbar' %>

  <body>
    <div class="background">

      <main>
        <%= yield %>
      </main>

      <footer>
        Have fun ! <%= link_to '©︎', new_admin_session_path %> 2020 Nanimiru
      </footer>
    </div>
  </body>

</html>