config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'homes/about'
  end
	devise_for :admins, controllers: {
		sessions:      'admin/sessions',
		passwords:     'admin/passwords',
	}

	devise_for :users, controllers: {
		sessions: 'public/sessions',
		passwords:     'public/passwords',
		registrations: 'public/registrations',
	}

	namespace :admin do

		root 'photos#index'
		resources :photos, only: [:show, :edit, :update] do
			resources :comments, only: [:update]
		end

		resources :users, only: [:index, :show]
		put 'users/:id' => 'users#update', as: 'user_update'
		get 'users/:id/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:id/followers' => 'relationships#followers', as: 'user_followers'

		get 'comments' => 'comments#index', as: 'comments'

	end

	scope module: :public do

		root 'photos#index'
		resources :photos, only: [:new, :create, :show, :edit, :update, :destroy] do
			resources :comments, only: [:create, :edit, :update, :destroy]
			resource :favorites, only: [:create, :destroy]
		end

		get 'about' => 'homes#about', as: 'about'

		get 'users/:name' => 'users#show', as: 'user'
		get 'users/:name/edit' => 'users#edit', as: 'user_edit'
		patch 'users/:name' => 'users#update'

		get 'users/:name/followings' => 'relationships#followings', as: 'user_followings'
		get 'users/:name/followers' => 'relationships#followers', as: 'user_followers'
		post 'follow/:name' => 'relationships#create', as: 'follow'
		delete 'unfollow/:name' => 'relationships#destroy', as: 'unfollow'

		get 'search' => 'photos#search', as: 'search'

		resources :inquiries, only: [:create]
		get 'contact' => 'inquiries#new', as: 'contact'
		get 'contact/finish' => 'inquiries#finish', as: 'contact_finish'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true,
           length: { maximum: 10 }

  attachment :image

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローされている人
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower

  # フォローした人
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!
  before_action :ensure_admin_user, only: [:show, :update]

  def index
    @users = User.all
  end

  def show
    @photos = @user.photos
  end

  def update
    if @user.is_active == true
      @user.update(is_active: false)
      redirect_back(fallback_location: root_path)
    else
      @user.update(is_active: true)
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def ensure_admin_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">

  <div class="admin_users">
    <h2 class="admin_users-name">Users</h2>

    <table class="admin_users-table">
      <% @users.each do |user| %>
        <tr>
          <td class="admin_users-table-image">
            <%= link_to admin_user_path(user) do %>
              <%= attachment_image_tag user, :image, class: "admin_users-table-image-content", format: 'jpeg', fallback: 'no-user-image.png' %>
            <% end %>
          </td>
          <td class="admin_users-table-name"><%= user.name %></td>
          <td class="admin_users-table-photo"><%= pluralize(user.photos.count, "photo") %></td>
          <td class="admin_users-table-follow">
            <%= link_to admin_user_followings_path(user), class: "admin_table-following" do %>
              <%= pluralize(user.follower.count, "following") %>
            <% end %>
          </td>
          <td class="admin_users-table-follow">
            <%= link_to admin_user_followers_path(user), class: "admin_table-follower" do %>
              <%= pluralize(user.followed.count, "follower") %>
            <% end %>
          </td>
          <td class="admin_users-table-btn">
            <% if user.is_active == true %>
              <%= link_to 'Open', admin_user_update_path(user), method: :put, class: "btn admin_users-table-btn-open" %>
            <% else %>
              <%= link_to 'Hide', admin_user_update_path(user), method: :put, class: "btn admin_users-table-btn-hide" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>

  </div>

</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <div class="admin_user-show-user">
        <div class="admin_user-show-user-image">
          <%= attachment_image_tag @user, :image, class: "admin_user-image-content", format: 'jpeg', fallback: 'no-user-image.png' %>
        </div>
        <div class="admin_user-show-user-name">
          <%= @user.name %>
        </div>
        <div class="admin_user-show-user-introduction">
          <%= @user.introduction %>
        </div>
        <div class="admin_user-show-user-follow">
          <div class="row">
            <div class="col-md-4 offset-md-2 px-0">
              <%= link_to user_followings_path(@user), class: "admin_user-follow-content" do %>
                <%= @user.follower.count %> <br>
                followings
              <% end %>
            </div>
            <div class="col-md-4 px-0">
              <%= link_to user_followers_path(@user), class: "admin_user-follow-content" do %>
                <%= @user.followed.count %> <br>
                followers
              <% end %>
            </div>
          </div>
        </div>
        <div class="admin_user-show-user-btn">
          <% if @user.is_active == true %>
            <!-- putは置換、patchは更新・変更・修正 -->
            <%= link_to 'Open', admin_user_update_path, method: :put, class: "btn admin_user-btn-open" %>
          <% else %>
            <%= link_to 'Hide', admin_user_update_path, method: :put, class: "btn admin_user-btn-hide" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="admin_user-show-photo">
        <div class="row">
          <% @photos.each do |photo| %>
            <div class="col-md-3 px-0">
              <%= attachment_image_tag photo, :image, class: "admin_user-photo-content", format: 'jpeg' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>